
const API='https://api.anthropic.com/v1/messages', MODEL='claude-sonnet-4-6';
let running=false, R={}, charts={}, demoMode=false, stopRequested=false;
const dotTimers={}, dotIntervals={};

const INDUSTRIES = {
  daycare: {
    label:'Daycare / Childcare', emoji:'🏫',
    unit:'childcare center', units:'childcare centers',
    capacity_label:'Capacity (children)', capacity_default:75, budget_default:600000,
    regulatory:'DECAL (GA Dept of Early Care & Learning)', regulatory_url:'decal.ga.gov',
    tiers_label:'Age Groups',
    tiers:['Infant–Pre-K','Infant–Kindergarten','Toddler–Pre-K'],
    compliance:'DECAL licensing, staff-to-child ratios, 35 sqft/child indoor, 75 sqft/child outdoor, food safety, background checks, CDA credentials',
    grants:'Georgia CAPS subsidy, USDA CACFP reimbursement, DECAL Quality Rated incentives, USDA Rural Development grants, local childcare coalitions',
    competitors:'Primrose Schools, KinderCare, Bright Horizons, local independent centers',
    financials:'tuition by age group (infant/toddler/preschool/pre-K), staff ratios, CACFP reimbursement, CAPS subsidy income, director salary',
    staffing:'licensed lead teachers (CDA credential), assistant teachers, director, cook',
    real_estate:'2,500–6,000 sqft, playground space (75 sqft/child outdoor), commercial kitchen, multiple classrooms, ADA-compliant restrooms',
    revenue_unit:'monthly tuition per child',
    price_label_primary:'Infant/mo', price_label_secondary:'Preschool/mo',
  },
  gas_station: {
    label:'Gas Station / C-Store', emoji:'⛽',
    unit:'gas station', units:'gas stations',
    capacity_label:'Fuel Pumps', capacity_default:8, budget_default:1500000,
    regulatory:'Georgia EPD, EPA Underground Storage Tank program, Fire Marshal, State Fuel Tax license',
    regulatory_url:'epd.georgia.gov',
    tiers_label:'Fuel Types',
    tiers:['Regular + Diesel','Regular + Premium + Diesel','Full Multi-Grade'],
    compliance:'EPA UST registration, fire code, state fuel tax license, ATF tobacco permit, EBT/SNAP approval, ADA, spill containment',
    grants:'EPA Brownfields grants, USDA Rural Business Development grants, USDA Rural Energy programs, SBA 7(a) loans',
    competitors:'Shell, BP, Circle K, Chevron, QuikTrip, RaceTrac, local independents',
    financials:'fuel margin per gallon (regular/premium/diesel), convenience store gross margin (~30%), car wash add-on, ATM fee income, lottery commission',
    staffing:'cashiers, shift supervisors, maintenance technician',
    real_estate:'1–2 acres, highway or arterial visibility, underground storage tank clearance, canopy space for pumps, truck access for fuel delivery',
    revenue_unit:'daily fuel gallons sold + c-store revenue',
    price_label_primary:'Fuel Margin', price_label_secondary:'C-Store/mo',
  },
  laundromat: {
    label:'Laundromat', emoji:'🫧',
    unit:'laundromat', units:'laundromats',
    capacity_label:'Washers (machines)', capacity_default:30, budget_default:350000,
    regulatory:'Local zoning, water/sewer utility agreements, fire code, ADA accessibility',
    regulatory_url:'local municipality',
    tiers_label:'Equipment Mix',
    tiers:['Standard (top-load focus)','Mixed (top & front-load)','Premium (large-capacity focus)'],
    compliance:'water/sewer capacity permit, drain permits, fire suppression, ADA accessibility, ventilation requirements, electrical capacity (400A+)',
    grants:'USDA Rural Business Development grants, SBA 7(a) loans, local economic development incentives, energy-efficiency utility rebates',
    competitors:'Speed Queen laundromats, Wash & Dry chains, local coin-ops, WaveMax franchise',
    financials:'revenue per machine per day, vend price by machine size, utility cost (water/gas/electric ~40% of revenue), wash-dry-fold service, attendant labor',
    staffing:'part-time attendants, maintenance technician',
    real_estate:'2,000–4,000 sqft, high-traffic strip mall, heavy water/gas lines, strong electrical service (200–400A), parking',
    revenue_unit:'revenue per machine per day',
    price_label_primary:'Wash Price', price_label_secondary:'Revenue/day',
  },
  car_wash: {
    label:'Car Wash', emoji:'🚗',
    unit:'car wash', units:'car washes',
    capacity_label:'Wash Bays', capacity_default:4, budget_default:1200000,
    regulatory:'Local zoning, water reclamation system, stormwater permit, EPA wastewater discharge, Fire Marshal',
    regulatory_url:'local municipality / EPA',
    tiers_label:'Service Tiers',
    tiers:['Express (tunnel only)','Full-Service','Express + Detail'],
    compliance:'water reclamation system (mandatory in most states), stormwater permit, EPA wastewater discharge, signage permits, fire code, ADA',
    grants:'EPA WaterSense rebates, SBA 7(a) loans, local economic development, USDA Rural Business grants, water utility conservation incentives',
    competitors:"Mister Car Wash, Zips Car Wash, Tommy's Express, Crew Carwash, local self-serve washes",
    financials:'cars per hour per bay, pricing by tier (basic/deluxe/premium), monthly membership/subscription revenue, detailing add-ons, fleet accounts',
    staffing:'wash attendants, cashiers, detailers, maintenance technician, manager',
    real_estate:'0.5–1.5 acres, high-traffic arterial, drive-through lane space, utility connections (water/sewer/electric), setback for stacking',
    revenue_unit:'cars washed per day × average ticket',
    price_label_primary:'Avg Ticket', price_label_secondary:'Member/mo',
  },
  restaurant: {
    label:'Restaurant / Food Service', emoji:'🍽️',
    unit:'restaurant', units:'restaurants',
    capacity_label:'Seating Capacity', capacity_default:60, budget_default:450000,
    regulatory:'Georgia Dept of Public Health, local health dept, Fire Marshal, liquor license (if applicable), ADA',
    regulatory_url:'dph.georgia.gov',
    tiers_label:'Service Format',
    tiers:['Fast Casual','Full Service / Dine-In','Counter Service + Delivery'],
    compliance:'food handler permits, commercial kitchen health inspection, fire suppression (Ansul) system, hood ventilation, ADA, grease trap, liquor license',
    grants:'SBA Restaurant Revitalization Fund, USDA Rural Business grants, local economic development, Georgia SBDC programs',
    competitors:'Local independent restaurants, regional fast-casual chains, national QSR franchises',
    financials:'revenue per seat, table turns per day, average check, food cost % (~28–35%), labor cost % (~30–35%), rent-to-revenue ratio (<10%)',
    staffing:'chef/kitchen manager, line cooks, servers, host, dishwasher, manager',
    real_estate:'1,500–4,000 sqft, commercial kitchen, parking (1 space/3 seats), grease trap, hood ventilation, health-dept-compliant layout',
    revenue_unit:'revenue per seat per day',
    price_label_primary:'Avg Check', price_label_secondary:'Rev/seat/day',
  },
  gym: {
    label:'Gym / Fitness Center', emoji:'💪',
    unit:'gym', units:'gyms',
    capacity_label:'Member Capacity', capacity_default:500, budget_default:500000,
    regulatory:'Local zoning, building occupancy certificate, ADA, fire code, personal trainer certification (NASM/ACE)',
    regulatory_url:'local municipality',
    tiers_label:'Membership Tiers',
    tiers:['Basic + Standard','Standard + Premium','Full-Service (all tiers + PT)'],
    compliance:'occupancy limits, ADA accessibility, equipment safety anchoring, emergency exits, ventilation/HVAC for exercise load, liability insurance',
    grants:'SBA 7(a) loans, local economic development incentives, USDA Rural Business grants, New Markets Tax Credits',
    competitors:'Planet Fitness, LA Fitness, Anytime Fitness, YMCA, CrossFit affiliates, local boutique studios',
    financials:'monthly memberships by tier, personal training packages, class/program fees, retail supplements, annual fee, churn rate (~3–5%/mo)',
    staffing:'personal trainers (NASM/ACE certified), front desk staff, group class instructors, maintenance, general manager',
    real_estate:'4,000–15,000 sqft, high-ceiling open floor, parking, locker rooms with showers, HVAC for heat load, ADA restrooms',
    revenue_unit:'monthly recurring membership revenue',
    price_label_primary:'Member/mo', price_label_secondary:'PT Session',
  },
  indoor_play: {
    label:'Indoor Play Area / FEC', emoji:'🎠',
    unit:'indoor play center', units:'indoor play centers',
    capacity_label:'Daily Visitor Capacity', capacity_default:200, budget_default:900000,
    regulatory:'Local fire marshal, ASTM F1487 equipment standards, ADA, food service permit (if café), state child safety regulations',
    regulatory_url:'local municipality / ASTM',
    tiers_label:'Admission Tiers',
    tiers:['Drop-In (hourly)','Memberships + Drop-In','Full FEC (memberships + parties + café)'],
    compliance:'CPSC and ASTM F1487 equipment safety standards, fire occupancy limits, ADA accessibility, food service health permit (if café), party room fire egress, liability waivers, staff-to-child supervision ratios',
    grants:'SBA 7(a) loans, USDA Rural Business Development grants, local economic development incentives, New Markets Tax Credits, tourism development grants',
    competitors:'Jump! Zone, Sky Zone, Urban Air Adventure Parks, Defy, Pump It Up, Rockin Jump, Altitude Trampoline Park, Chuck E. Cheese, local bounce house venues',
    financials:'hourly admission by age/height, birthday party packages ($300-$800), monthly memberships, café/concession revenue, arcade/token revenue, special event rentals',
    staffing:'party hosts, floor monitors (CPR certified), front desk/cashiers, café staff, birthday party coordinator, general manager, maintenance technician',
    real_estate:'8,000–25,000 sqft, high ceilings (20+ ft for climbing/trampoline zones), anchor or strip mall, large parking, ADA restrooms, separate party rooms, kitchen/café area',
    revenue_unit:'daily admission revenue + party bookings',
    price_label_primary:'Admission/child', price_label_secondary:'Party Package',
  },
  dry_cleaning: {
    label:'Dry Cleaning / Laundry Service', emoji:'👔',
    unit:'dry cleaning business', units:'dry cleaning locations',
    capacity_label:'Garments/Day Capacity', capacity_default:250, budget_default:420000,
    regulatory:'EPA PERC regulations (40 CFR Part 63 Subpart M), state dry cleaning fund registration, hazardous waste disposal permit, fire marshal, air quality permit',
    regulatory_url:'epa.gov / state environmental agency',
    tiers_label:'Service Mix',
    tiers:['Dry Clean + Press Only','Full Service (dry clean + laundry + alterations)','Premium (same-day + delivery + alterations)'],
    compliance:'EPA perchloroethylene (PERC) or wet-cleaning compliance, state dry cleaning environmental fund registration, hazardous waste manifest, fire code for solvent storage, ADA, wastewater discharge permit',
    grants:'EPA Brownfields grants for PERC remediation, SBA 7(a) loans, state dry cleaning environmental fund low-interest loans, USDA Rural Business grants, green cleaning transition incentives',
    competitors:'Martinizing Dry Cleaning, CD One Price Cleaners, Tide Cleaners, Lapels Dry Cleaning, Zips Dry Cleaning, local independents, on-demand apps (Rinse, Laundry Care)',
    financials:'price per garment by type (suit $12-20, shirt $5-8, dress $15-25), alterations revenue, pickup/delivery premium, monthly commercial account contracts, wedding/specialty garment revenue',
    staffing:'dry cleaning technician (certified), pressers, customer service/counter staff, delivery driver (if delivery), alterations specialist, store manager',
    real_estate:'1,200–3,500 sqft, strip mall or standalone, drive-through window (high value), adequate ventilation for solvents, utility connections (gas/electric/water), ADA, parking',
    revenue_unit:'revenue per garment + alterations',
    price_label_primary:'Avg Ticket/Order', price_label_secondary:'Commercial Acct/mo',
  },
};

// ── MULTI-PROVIDER CONFIG ────────────────────────────────────
const PROVIDERS = {
  anthropic: {
    label: 'Anthropic (Claude)',
    url: 'https://api.anthropic.com/v1/messages',
    model_default: 'claude-sonnet-4-5',
    headers: key => ({'x-api-key':key,'anthropic-version':'2023-06-01','Content-Type':'application/json','anthropic-dangerous-direct-browser-access':'true'}),
    buildBody: (system,user,model) => ({model,max_tokens:8192,system,messages:[{role:'user',content:user}]}),
    extractText: d => (d.content||[]).filter(b=>b.type==='text').map(b=>b.text).join('\n'),
    extractStop: d => d.stop_reason,
  },
  openai: {
    label: 'OpenAI (GPT-4o)',
    url: 'https://api.openai.com/v1/chat/completions',
    model_default: 'gpt-4o',
    headers: key => ({'Authorization':'Bearer '+key,'Content-Type':'application/json'}),
    buildBody: (system,user,model) => ({model,max_tokens:8192,messages:[{role:'system',content:system},{role:'user',content:user}]}),
    extractText: d => d.choices?.[0]?.message?.content||'',
    extractStop: d => d.choices?.[0]?.finish_reason,
  },
  gemini: {
    label: 'Google Gemini',
    url: key => `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key=${key}`,
    model_default: 'gemini-1.5-pro',
    headers: () => ({'Content-Type':'application/json'}),
    buildBody: (system,user,model) => ({contents:[{role:'user',parts:[{text:system+'\n\n'+user}]}],generationConfig:{maxOutputTokens:8192}}),
    extractText: d => d.candidates?.[0]?.content?.parts?.[0]?.text||'',
    extractStop: d => d.candidates?.[0]?.finishReason,
  },
  openai_compat: {
    label: 'OpenAI-Compatible (Local)',
    url_custom: true,
    model_default: 'local-model',
    headers: key => ({'Authorization':'Bearer '+key,'Content-Type':'application/json'}),
    buildBody: (system,user,model) => ({model,max_tokens:8192,messages:[{role:'system',content:system},{role:'user',content:user}]}),
    extractText: d => d.choices?.[0]?.message?.content||'',
    extractStop: d => d.choices?.[0]?.finish_reason,
  },
};

// ── RESPONSE CACHE ──────────────────────────────────────────
